version: 0.1
 
phases:
  build:
    commands:
      - aws s3 sync --exact-timestamps --delete contents s3://test-hsci-basicauth
      - aws cloudfront create-invalidation --distribution-id E1YMLQYN76M5KR --paths "/*"
